### ISSUE TITLE
Validate support file content

### ISSUE THREAD

**Issue by jbuckle** [NEU-DSG/tapas_rails#11]
Right now we just assume that everything in the support file zip will be an image and treat it as such on ingest.  

There are two parts to this: 

* We should make some effort to ensure that we are actually ingesting images, even if it is kind of flaky and even if the Drupal application makes the guarantee that that is all that will ever be sent. 

* What image formats do we support?  This is a question for @sarahjeansweeney and @dhscratch I imagine.

**Comment by dhscratch** [comment]
Currently, png, jpg, jpeg are allowed.

**Comment by jbuckle** [comment]
Thanks Ben
